service: autopres-tool
plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
  - serverless-iam-roles-per-function

custom:
  pythonRequirements:
    dockerizePip: true
    # slim: true
    strip: true
  globalConstants:
    LAMBDA_ARN_PREFIX: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}
    CREATEPRES_LAMBDA_ARN: ${self:custom.globalConstants.LAMBDA_ARN_PREFIX}-createpres

provider:
  name: aws
  runtime: python3.8
  region: eu-west-1
  stage: dev

functions:
  gateway:
    handler: gateway.handler
    timeout: 30
    events:
      - http:
          path: createpres
          method: post
    environment:
      CREATEPRES_LAMBDA_ARN: ${self:custom.globalConstants.CREATEPRES_LAMBDA_ARN}
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - lambda:InvokeFunction
        Resource: "*"
  createpres:
    handler: createpres.handler
    timeout: 900
# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
